language: objective-c
branches:
  only:
    - master
before_install:
  - sudo gem install bundler
  - git submodule update --init --recursive
script: bundle exec rake spec
notifications:
  email: false
  slack: realmio:vPdpsG9NLDo2DNlbqtcMAQuE
matrix:
  include:
    - osx_image: xcode6.4
      env: TRAVIS_SWIFT_VERSION=1.2
    - osx_image: xcode7
      env: TRAVIS_SWIFT_VERSION=2.0
