language: objective-c
xcode_workspace: SourceKitten.xcworkspace
xcode_scheme: sourcekitten
osx_image: xcode611
before_install: true
install: true
git:
  submodules: false
script: BUILD_TOOL=xctool script/cibuild
notifications:
  email: false
